import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{createPortal}from'react-dom';
import{ArrowLeft,ArrowRight,Check,ChevronDown,Menu,Target,Volume2,VolumeX,X,Coins,Scale,MessageCircleWarning}from'lucide-react';
import'./styles.css';

const A='/assets/';
const tabs=['The leak','What it means','Three ledgers','Five questions','Exam lens'];
const ledgers=[
['The Financial Ledger','05.png','Fines and penalties — privacy regulators often fine as a percentage of company revenue, while payment card schemes fine per month and per incident. Also covers remediation and re-audit costs, contract damages, higher fees imposed by financial acquirers going forward, insurance excess, and the rework bill itself. Example: a single card-data security incident — forensic investigation, regulatory fines, reissuing compromised cards to every affected customer — can dwarf the entire budget a project spent on conformance activities like training and testing.'],
['The Legal Ledger','06.png','Regulatory enforcement action, orders to stop processing entirely — for a payments pilot, effectively an order to stop existing — loss of a license or certification, personal liability for responsible officers under some regulatory regimes, lawsuits from genuinely harmed customers, and contract termination for cause. Example: an incorrect allergen label reaching a customer with a genuine allergy isn\'t a documentation error to quietly correct — it\'s a potential lawsuit, and depending on severity, potential criminal liability for the individuals responsible. PMBOK® 8 lists "legal, regulatory, or compliance" among the recognized reasons a project gets terminated outright.'],
['The Reputational Ledger','07.png','PMBOK® 8\'s own language: long-term harm to the organization\'s reputation or performance. Shows up as stakeholder trust evaporating almost overnight, customer churn, press coverage that outlives the actual fix by months or years, and harder audits and warier partnerships in every project that follows. This is the one ledger that compounds. A financial fine is paid once. A legal judgment is settled once. Reputational damage raises the cost of everything that comes after it — every future audit is more skeptical, every future partner asks harder questions. It\'s the ledger that never actually closes.']
];
const reveals={
 hook:{title:'Analyze the Consequences of Noncompliance',image:'02.png',text:'Noncompliance works exactly the same way. This lesson is about seeing the full cost of a compliance failure before it happens — not just the fine, but the legal exposure and the reputational damage sitting alongside it, each one different in kind, and one of them dangerous precisely because it never stops compounding.'},
 meaning:{title:'Analyze Before the Response Is Chosen',image:'04.png',text:'This enabler asks the project manager to analyze the consequences of noncompliance — run per row of the compliance register, and completed before response strategies are chosen. This ordering matters: severity is what calibrates how much prevention investment is actually justified. A risk analyzed only after the response is already decided gets whatever budget was left over, not the budget its actual severity demands. Consequence analysis runs across three distinct ledgers.'},
 questions:{title:'Five Questions, Three Jobs',image:'09.png',questions:['What happens if this specific requirement fails?','Who is actually harmed?','What does the regulator\'s response look like?','What does it cost across all three ledgers?','And over what time horizon — because external failures bleed after the project itself has closed, which is exactly why this analysis has to be measured over the product\'s full life, not just the project\'s timeline.'],intro:'The answers to these five questions do three distinct jobs elsewhere in compliance management:',jobs:['They set the actual impact scores a compliance risk carries in risk analysis — a risk where the harm lands on an actual person earns a severity score reflecting genuine human harm, not just schedule slippage.','They justify the prevention budget spent to avoid the failure — catastrophic financial and legal exposure is what makes an expensive prevention investment look, in comparison, genuinely cheap.','And they decide escalation speed — a compliance breach carrying a statutory notification clock escalates in hours, immediately, not at the next scheduled steering committee meeting.']},
 exam:{title:'Analyze the Consequences of Noncompliance',image:'11.png',text:'Analyzing the consequences of noncompliance runs across three ledgers for every entry in the compliance register: the financial ledger of fines, remediation, and rework; the legal ledger of enforcement, license loss, and the termination cliff PMBOK® 8 names explicitly; and the reputational ledger — the one ledger that compounds, raising the cost of everything that follows rather than settling once. Five questions — what fails, who\'s harmed, the regulator\'s likely response, the cost, and the time horizon — don\'t just describe the risk. They calibrate the actual impact score it carries, justify the prevention budget spent to avoid it, and determine how fast it needs to be escalated when it happens. A compliance risk analyzed honestly across all three ledgers, before a response is chosen, is what keeps a small, ignored gap from becoming the cliff edge PMBOK® 8 warns about.',bullets:['Three ledgers: financial (fines, remediation, rework), legal (enforcement, license loss, termination), reputational (the only one that compounds)','Consequence analysis happens before response strategy is chosen, so severity — not leftover budget — drives prevention investment','Five questions: what fails, who\'s harmed, regulator response, cost across all three ledgers, time horizon','A statutory notification clock overrides standard escalation cadence entirely — hours, not the next scheduled meeting']}
};
const quiz={q:'Scenario: A project team discovers a data breach affecting customer records. Regulatory law requires disclosure within 72 hours of discovery. The team\'s standard practice is to raise issues at the next scheduled monthly steering committee meeting, which is 18 days away. What does consequence analysis reveal about the correct response here?',a:['Standard escalation timing is appropriate, since the breach can be documented and addressed at the next steering meeting','The legal ledger\'s statutory notification deadline demands immediate escalation, in hours, regardless of the standard reporting cadence','The financial ledger takes priority, so the team should first calculate the cost of fines before deciding when to escalate','Since this is a reputational issue, the team should prepare a public statement before escalating internally'],good:'Correct! This is exactly what a statutory clock means in practice — a legal deadline of 72 hours makes the standard monthly cadence irrelevant. Escalation needs to happen in hours, precisely because consequence analysis reveals this failure carries a legal deadline that standard practice doesn\'t account for.',bad:'Reconsider — waiting for the standard cadence would itself become a separate compliance violation; calculating financial cost doesn\'t change a legal deadline already ticking; and reputational management doesn\'t take priority over the immediate statutory obligation.'};

function Modal({d,close,read}){
 const[step,setStep]=useState(0),splitQuestions=Boolean(d.questions),hasSecondStep=splitQuestions||Boolean(d.bullets);
 return createPortal(<div className="modal-backdrop" onClick={close}><section className={`focus-modal ${splitQuestions?'questions-modal':''}`} onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={close} aria-label="Close"><X/></button>
  {splitQuestions?step===0?<><img className="modal-illustration" src={A+d.image}/><h3>Five Questions</h3><div className="question-breakdown"><ol>{d.questions.map(x=><li key={x}>{x}</li>)}</ol></div></>:<><h3>Three Jobs</h3><div className="question-breakdown jobs-step"><p>{d.intro}</p><ul>{d.jobs.map(x=><li key={x}>{x}</li>)}</ul></div></>:step===0?<><img className="modal-illustration" src={A+d.image}/><h3>{d.title}</h3><div className="modal-copy"><p>{d.text}</p></div></>:<div className="memory-step"><h3>Exam-Relevant Enablers to Remember</h3><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}
  <div className="modal-actions">{step===1&&<button className="modal-back" onClick={()=>setStep(0)}><ArrowLeft/> Back</button>}{hasSecondStep&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{read();close()}}>Mark as read <Check/></button>}</div>
 </section></div>,document.body)
}
function Quiz({finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{quiz.q}</h3><div className="answers vertical">{quiz.a.map((x,i)=><button key={x} onClick={()=>setP(i)} className={p===i?(i===1?'correct':'wrong'):''}><span>{'ABCD'[i]}</span>{x}</button>)}</div>{p!==null&&<><p className={`feedback ${p===1?'good':'bad'}`}>{p===1?quiz.good:quiz.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
const ledgerIcons=[Coins,Scale,MessageCircleWarning];
function App(){
 const[s,setS]=useState(0),[done,setDone]=useState(Array(5).fill(false)),[modal,setModal]=useState(),[seen,setSeen]=useState([]),[quizOpen,setQuizOpen]=useState(false),[sound,setSound]=useState(true);
 const mark=i=>setDone(v=>v.map((x,n)=>n===i?true:x));
 const go=i=>{if(i>=0&&i<5&&(i===0||done[i-1]))setS(i)};
 const read=()=>{if(modal?.index!==undefined){const n=[...new Set([...seen,modal.index])];setSeen(n);if(n.length===3)mark(2)}else if(s===3){setQuizOpen(true)}else mark(s)};
 return <div className="app"><header><button className="course"><Menu/> Project Management Professional <ChevronDown/></button><div className="dots">{Array.from({length:10},(_,i)=><span key={i} className={i<9?'past':i===9?'current':''}>{i<9&&<Check/>}</span>)}</div><div className="tools"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}{sound?'Sound on':'Sound off'}</button><button>Quit</button></div></header><div className="lesson-frame"><div className="section-label">SECTION {s+1} OF 5</div><nav style={{gridTemplateColumns:'repeat(5,1fr)'}}>{tabs.map((t,i)=><button key={t} onClick={()=>go(i)} disabled={i&&!done[i-1]} className={i===s?'active':done[i]?'complete':''}>{done[i]&&<Check/>}{t}</button>)}</nav><main>
 {s===0&&<section className="hero"><div><p className="eyebrow">LESSON 4.11.5</p><h1>Analyze the Consequences of Noncompliance</h1><p>A homeowner ignoring a small roof leak isn't just risking a wet ceiling. The real cost is the mold that grows behind the drywall, the structural rot nobody sees until the beam gives way, and the insurance claim that gets denied because the damage was "preventable neglect." One small ignored problem, three completely different kinds of cost, compounding quietly the longer it goes unaddressed.</p><button className="primary" onClick={()=>setModal(reveals.hook)}>Reveal the full cost <ArrowRight/></button></div><img src={A+'01.png'}/></section>}
 {s===1&&<section className="hero"><div><h2>The Order Matters</h2><p>The order this happens in matters as much as the analysis itself — do it after the response is already picked, and the analysis arrives too late to actually change anything.</p><button className="primary" onClick={()=>setModal(reveals.meaning)}>Reveal what this enabler asks <ArrowRight/></button></div><img src={A+'03.png'}/></section>}
 {s===2&&<section className="components"><p className="eyebrow">THE THREE LEDGERS</p><h2>The Full Cost of a Compliance Failure</h2><p>Three distinct ledgers make up the full cost of a compliance failure. Click each to explore.</p><div className="direct-card-grid count-3">{ledgers.map((x,i)=>{const I=ledgerIcons[i];return <button className={`direct-detail-card ${seen.includes(i)?'visited':''}`} onClick={()=>setModal({title:x[0],image:x[1],text:x[2],index:i})} key={x[0]}><span className="direct-card-icon"><I/></span><span className="direct-card-copy"><small>{seen.includes(i)?<><Check/> READ</>:String(i+1).padStart(2,'0')}</small><strong>{x[0]}</strong></span><ArrowRight className="direct-card-arrow"/></button>})}</div></section>}
 {s===3&&<section className="hero"><div><p className="eyebrow">THE ANALYSIS IN PRACTICE: FIVE QUESTIONS</p><h2>Five Questions Drive the Analysis</h2><p>For every row in the compliance register, five questions drive the analysis — and the answers do more than just describe the risk.</p><button className="primary" onClick={()=>setModal(reveals.questions)}>Reveal the five questions <ArrowRight/></button></div><img src={A+'08.png'}/></section>}
 {s===4&&<section className="hero"><div><p className="eyebrow">EXAM LENS</p><h2>Back to that roof leak one more time —</h2><p>because the cost was never just the wet ceiling. It was everything that kept compounding behind the wall while nobody was looking.</p><button className="primary" onClick={()=>setModal(reveals.exam)}>Reveal the exam lens <ArrowRight/></button></div><img src={A+'10.png'}/></section>}
 </main><footer><button onClick={()=>go(s-1)} disabled={!s}><ArrowLeft/> Previous</button><button className="continue" onClick={()=>go(s+1)} disabled={!done[s]}>{s===4?'Complete':'Continue'} <ArrowRight/></button></footer></div>{modal&&<Modal d={modal} close={()=>setModal()} read={read}/>} {quizOpen&&<Quiz finish={()=>{setQuizOpen(false);mark(3)}}/>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
